In [1]:
import numpy

In [5]:
numpy.array([1,2,3],dtype=numpy.float)

array([ 1.,  2.,  3.])

In [3]:
numpy.float32(1.0/9.0)

0.11111111

    vec4 packFloatToVec4(const float value) {
      const vec4 bitSh = vec4(256.0*256.0*256.0, 256.0*256.0, 256.0, 1.0);
      const vec4 bitMsk = vec4(0.0, 1.0/256.0, 1.0/256.0, 1.0/256.0);
      vec4 res = fract(value * bitSh);
      res -= res.xxyz * bitMsk;
      return res;
    }


    float unpackFloatFromVec4(const vec4 value) {
      const vec4 bitSh = vec4(1.0/(256.0*256.0*256.0), 1.0/(256.0*256.0), 1.0/256.0, 1.0);
      return(dot(value, bitSh));
    }

In [20]:
def vec4(a,b,c,d):
    return numpy.array([a,b,c,d], dtype=numpy.float32)

def packFloatToVec4(value):
    bitSh = vec4(256.0*256.0*256.0, 256.0*256.0, 256.0, 1.0)
    bitMsk = vec4(0.0, 1.0/256.0, 1.0/256.0, 1.0/256.0)
    res = numpy.modf(value * bitSh)[0]
    res -= vec4(res[0], res[0], res[1], res[2]) * bitMsk
    return res

def unpackFloatFromVec4(value):
    bitSh = vec4(1.0/(256.0*256.0*256.0), 1.0/(256.0*256.0), 1.0/256.0, 1.0)
    return numpy.dot(value, bitSh)

foo = unpackFloatFromVec4(vec4(.555, .666, .777, .888))
    
packFloatToVec4(foo)



array([ 0.        ,  0.546875  ,  0.10546875,  0.890625  ], dtype=float32)

In [14]:
import math

In [15]:
math.fract

AttributeError: 'module' object has no attribute 'fract'

In [17]:
math.modf(1.1)

(0.10000000000000009, 1.0)

In [19]:
numpy.modf(vec4(1.1,2.2,3.3,4.4))[0]

array([ 0.10000002,  0.20000005,  0.29999995,  0.4000001 ], dtype=float32)